readme.md
Beware: update the file name `execption` to `exception` inside the wiki as it was not forked along with this repo.
=> Fix typo on Exceptions link

.gitignore, app/Containers/Contact/Tasks/SendContactUsEmailTask.php, app/Containers/Contact/UI/WEB/Views/EmailTemplates/contactUs.blade.php
Overwriting $email->from breaks smtp services such as AWS SES which needs a verified sender.
Email object was missing $email->to field, which triggers an Exception
=> Contact form fixes

app/Containers/Authentication/Middlewares/WebAuthentication.php
such as...
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function setCookie() on null
in /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:136
...whilst trying to access a protected web view
=> Route level middleware doesn't prepare a response and causes errors

app/Ship/Engine/Loaders/MiddlewaresLoaderTrait.php
Avoid to override middleware when Containers middleware service providers are loaded. Closes #102
=> Prevent overide middlewares fix

resources/lang/ar/auth.php, resources/lang/ar/pagination.php, resources/lang/ar/passwords.php, resources/lang/ar/validation.php, resources/lang/fr/auth.php, resources/lang/fr/pagination.php, resources/lang/fr/passwords.php, resources/lang/fr/validation.php
This closes #118, now we have full translations strings for the supported languages... mainly on validation messages... these translations files were taken from this repo:
https://github.com/caouecs/Laravel-lang
=> add missing translations files

.env.travis, .travis.yml, app/Containers/Authentication/UI/WEB/Tests/Functional/UserLoginTest.php, app/Containers/Authentication/UI/WEB/Tests/Functional/UserLogoutTest.php, app/Containers/Authentication/UI/WEB/Views/login.blade.php, app/Containers/Localization/Configs/localization.php, app/Containers/Localization/Resources/Languages/es/messages.php, app/Containers/Welcome/UI/WEB/Tests/Acceptance/WelcomeTest.php, app/Ship/Parents/Requests/RequestTrait.php, resources/lang/ar/auth.php, resources/lang/ar/pagination.php, resources/lang/ar/passwords.php, resources/lang/ar/validation.php, resources/lang/es/auth.php, resources/lang/es/pagination.php, resources/lang/es/passwords.php, resources/lang/es/validation.php, resources/lang/fr/auth.php, resources/lang/fr/pagination.php, resources/lang/fr/passwords.php, resources/lang/fr/validation.php
This PR can solve #54 and #74 (based on the #115 PR too). Now we can get rid of the WithoutMiddleware trait on web routes testing and now we have correct form validations error displaying on web routes. In the future maybe we will have displaying errors from FormRequests authorization, but at the moment everything is ok. This PR is based on the DingoAPI documentation, and specifically [this](https://github.com/dingo/api/blob/master/src/Http/FormRequest.php) class... the future problem commented could be solved checking the Dingo Formrequest class again.
=> fix displaying form requests validation errors on web routes

app/Ship/Engine/Traits/ResponseTrait.php
This brings back the missing **Relations** feature described on [apiato Supported Parameters docs](http://apiato.io/C.features/supported-parameters/).
=> append related models to responses based on input request

app/Ship/Engine/Traits/ResponseTrait.php
fixes a "bug", where the "defaultIncludes" of a `Transformer` are ignored if you use the `?include=xxx` query parameter on an URI..
=> [fix] DefaultIncludes

app/Ship/Engine/Traits/ResponseTrait.php
* Adds the `includes` field to the `meta` block within a transformer. This field indicates all availabe includes for this resource
* Adds the `custom` field to the `meta` block. Can contain application/user-specific information
=> Enhance Transformer

app/Containers/User/Actions/GetMyProfileAction.php, app/Containers/User/Data/Seeders/UserPermissionsSeeder_1.php, app/Containers/User/UI/API/Controllers/Controller.php, app/Containers/User/UI/API/Requests/GetMyProfileRequest.php, app/Containers/User/UI/API/Routes/GetMyProfile.v1.private.php, app/Containers/User/UI/API/Tests/Functional/ListAllAdminsTest.php
Currently you need to call `/users/ID` in order to get your own profile. However, if you do not know your `ID`, it is not possible to get it ;)
Therefore, i have created a `/my/profile` route, which returns the respective profile for the currently logged in user!
I know, that there is a dependency between the `User` and `Authentication` Container, but i need to get the logged in user!
=> Add route to easily access your "own" profile

config/filesystems.php
Receiving following notice message after cloning the repository.
```
Notice: Undefined index: host in /Volumes/Development/projects/2017/opensource/apiato/config/filesystems.php on line 66
PHP Notice:  Undefined index: host in /Volumes/Development/projects/2017/opensource/apiato/config/filesystems.php on line 66
```
This is due to `.env` not exist yet. I think it's a good practice to reduce numbers of notice messages - i know when creating new project this won't happen. Just to be safe for those want to contribute to repository.
=> Set default value when load APP_URL

app/Containers/Application/UI/CLI/Commands/Name.php, app/Containers/Application/composer.json
This PR refer to issue #189 .
What it does basically to rename application namespace properly since naming convention used in [apiato/config/app.php](https://github.com/apiato/apiato/blob/master/config/app.php) and [apiato/bootstrap/app.php](https://github.com/apiato/apiato/blob/master/bootstrap/app.php) is not a standard namespaces used in Laravel default setup.
=> Fix namespace naming

app/Ship/Parents/Repositories/Repository.php
This fix lets requestors disable pagination by simply adding `?limit=0` to the URL. Otherwise it is not possible to circumvent a paginated resultset, if the dev used `return $repository->paginate()`.
This can be handy, if a full-blown client with stable and broadband connection would like to fetch all data. Mobile clients, however, would still get a paginated result!
=> Disable Pagination on Requests

app/Containers/Authorization/composer.json
this updates to the latest 1.x version of the laravel-permission package.
Tests still pass..
Keep in mind, that this package is now in 2.4.x version available. However, a migration from 1.x to 2.x is not easily possible.. Maybe the `Authorization` container needs to be rebuild from scratch!?
=> bump laravel-permission version to latest 1.x version

docs/_docs/getting-started/installation.md
A reminder to create `.env` in laradock folder in case it was skipped or forgotten during laradock installation.
I had errors when I installed apiato the first time, and took me a while to realize that it was caused by not having `.env` file.
N/A
=> Add reminder to create .env in laradock folder

app/Containers/Authorization/Configs/permission.php, app/Ship/Configs/fractal.php, composer.json, docs/_docs/components/providers.md, docs/_docs/miscellaneous/faq.md, docs/_docs/miscellaneous/upgrade-guide.md
Fixes the problem with `config` files not being correctly loaded! This is caused by laravels newly introduced `Auto-Discovery` feature..
Basically, this PR turns `AD` off (i.e., it marks all packages to be not discovered any more).
Minor:
- moved `fractal.php` config file to `Ship/Configs`
- moved `permission.php` config file to `Containers/Authorization`
- updated docs to reflect the changes to auto-discovery
- formatting config files
=> fix auto-discovery issue

app/Ship/Configs/apiato.php, app/Ship/Kernels/HttpKernel.php, app/Ship/Middlewares/Http/ProcessETagHeadersMiddleware.php, docs/_docs/getting-started/requests.md
This PR adds an (optional) ETag Middleware.
This middleware appends an `ETag` HTTP Header field with a hash of the response body. If a client sends an `If-None-Match` HTTP Header with an ETag, this ETag is compared with the calculated one.
If those ETags match, the content has not changed --> The response is discarded (empty body) and an HTTP 304 (not modified) is returned.
Can be enabled/disabled (default = disabled) in `App/Ship/Configs/apiato.php` file
=> add (optional) "ETag Middleware"

CHANGELOG.md, app/Containers/User/UI/API/Tests/Functional/RegisterUserTest.php, app/Containers/User/UI/API/Tests/Functional/UpdateUserTest.php, app/Ship/Configs/optimus.heimdal.php, app/Ship/Exceptions/Builders/ExceptionBuilder.php, app/Ship/Exceptions/Formatters/AuthenticationExceptionFormatter.php, app/Ship/Exceptions/Formatters/AuthorizationExceptionFormatter.php, app/Ship/Exceptions/Formatters/ExceptionFormatter.php, app/Ship/Exceptions/Formatters/HttpExceptionFormatter.php, app/Ship/Exceptions/Formatters/MethodNotAllowedExceptionFormatter.php, app/Ship/Exceptions/Formatters/UnprocessableEntityHttpExceptionFormatter.php, app/Ship/Exceptions/Formatters/ValidationExceptionFormatter.php, docs/_docs/components/exceptionformatters.md
This PR provides the "main implementation" for the "Better Exceptions" for Apiato.
This code relies on the PR that is already provided in `apiato/core` and adds the `ExceptionFormatters`.
This PR allows to customize (i.e., adapt) the way, `Exceptions` are displayed to clients. Thereby, not only the structure itself, but also the available fields of the message can be easily adjusted to your needs. Furthermore, developers may add custom `Formatters` for their own exceptions!
Minor Changes:
- Adapted some "texts" in the `Tests` in order to comply with the changes
- Updated the `CHANGELOG` file
- Added a new Section to the `Docs` to explain the usage of the `ExceptionFormatters`
=> Better Exceptions

app/Ship/Middlewares/Http/ValidateJsonContent.php
This PR slightly adapts the `ValidateJsonContent` middleware.
Changes:
If the config flag `apiato.requests.force-accept-header` is set to `true` but it is not sent to the API, throw an `Exception` immediately.. In this case, the request does not need to be processed - because it will fail (preconditions are not met)
=> Change Middleware

CHANGELOG.md, app/Containers/Localization/Configs/localization-container.php, app/Containers/Localization/Middlewares/LocalizationMiddleware.php, app/Containers/Localization/Models/Localization.php, app/Containers/Localization/Models/Region.php, app/Containers/Localization/Resources/Languages/en-GB/messages.php, app/Containers/Localization/Tasks/GetAllLocalizationsTask.php, app/Containers/Localization/UI/API/Transformers/LocalizationTransformer.php, app/Containers/Welcome/Actions/FindMessageForApiRootVisitorAction.php, app/Containers/Welcome/Actions/FindMessageForApiV1VisitorAction.php, docs/_docs/features/localization.md
This PR improves the currently available `LocalizationMiddleware` as well as the associated `GET /localizations` route.
Major:
- The structure of the `supported_languages` in the config file now supports "regions" (e.g., `en-GB`) as well. **Unfortunately, this is not backwards-compatible!**
- The middleware logic is highly improved in order to support regions as well.
- Added a new `Region` model in order to reflect these changes
- The `GET /localizations` route now outputs the (possibly) defined "regions" as well.
- Updated the docs and changelog accordingly
Minor:
- Let the `Welcome` container use the `trans(...)` method in order to show the translation in action
=> [Improvement] Localization

CHANGELOG.md, app/Containers/Authentication/UI/API/Routes/Logout.v1.public.php
This PR makes the `/logout` route use `DELETE` instead of `POST` in order to be more RESTful..
=> Make LOGOUT use DELETE

CHANGELOG.md, app/Ship/Configs/apiato.php, app/Ship/Exceptions/UnsupportedFractalIncludeException.php, app/Ship/Parents/Transformers/Transformer.php
This PR fixes the bug mentioned in https://github.com/apiato/apiato/issues/203
Imagine the `UserTransformer` that provides an `include` parameter for `roles`. If the client now requests `?include=role` (note the missing `s`!), this would result in an Exception, that respective method (`includeUser()`) could not be found.
Mainly this fix just overrides the already existing method from `Fractal` and adds an additional Exception block to this. I initially submitted a PR to `league/fractal` in order to fix this issue but it was never merged..
The behavior to `throw an exception` or just `exclude this invalid include parameter` can be customized with a newly added config flag ( `apiato.requests.force-valid-includes`).
More details can be found in the mentioned issue above!
=> Fix Transformer Include Bug

CHANGELOG.md, app/Containers/User/UI/API/Controllers/Controller.php, app/Containers/User/UI/API/Transformers/MyselfTransformer.php
This PR adds a new `MyselfTransformer` for the "my own Profile" (`/user/profile`) route. This makes adding "private information" (e.g., configuration settings, ...) to this route much easier, as there is a dedicated `Transformer` for this route.
Otherwise, this would require `if/else` blocks in the `UserTransformer`, which could be hard to read / maintain..
=> Add MyselfTransformer

CHANGELOG.md, app/Containers/Authorization/Actions/CreateRoleAction.php, app/Containers/Authorization/Data/Migrations/2017_10_27_091547_update_roles_table.php, app/Containers/Authorization/Data/Seeders/AuthorizationRolesSeeder_2.php, app/Containers/Authorization/Models/Role.php, app/Containers/Authorization/Tasks/CreateRoleTask.php
This PR adds an additional `level` field to `Role` model.
This will allow us to define some kind of "hierarchy" for the `Role` mdoels (e.g., an `admin` is "better" than a `manager`).
Furthermore, this would allow us to use this `level` information on the requests in order to check, if a client has _at least_ the `level x` (e.g,. he must have at least level 100 to access this route).
=> add LEVEL to ROLE

app/Containers/User/Actions/ForgotPasswordAction.php, app/Containers/User/Actions/ResetPasswordAction.php, app/Containers/User/Configs/user-container.php, app/Containers/User/Mails/Templates/user-forgotPassword.blade.php, app/Containers/User/Mails/UserForgotPasswordMail.php, app/Containers/User/Tasks/CreatePasswordResetTask.php, app/Containers/User/Tasks/FindUserByEmailTask.php, app/Containers/User/Tasks/ResetPasswordTask.php, app/Containers/User/UI/API/Controllers/Controller.php, app/Containers/User/UI/API/Requests/ForgotPasswordRequest.php, app/Containers/User/UI/API/Requests/ResetPasswordRequest.php, app/Containers/User/UI/API/Routes/ForgotPassword.v1.public.php, app/Containers/User/UI/API/Routes/ResetPassword.v1.public.php
I added 2 public api endpoints `/forgotpassword` and `/resetpassword`.
To keep link generation dynamic (for multiple client applications) I do inject a reseturl variable from the client into the email, which opens an exploit vector since this is an open endpoint. I tried to avoid exploitation by a config variable to hold all allowed reseturls to prevent malicious urls in the email. Not sure if that is the right approach?
I tested this in my own application but haven't been able to provide automated tests. Any hints?
Would these changes invoke changes in the docs and if so how and where?
Thanks, Yal
=> [Feature] forgot and reset password endpoints

CHANGELOG.md, app/Ship/Exceptions/Codes/ApplicationErrorCodes.php, app/Ship/Exceptions/Codes/ApplicationErrorCodesTable.php, app/Ship/Exceptions/Codes/CustomErrorCodesTable.php, app/Ship/Exceptions/Codes/ErrorCodeManager.php, app/Ship/Parents/Exceptions/ErrorCodesTable.php
This PR offers the possibility to maintain all `codes` for exceptions in one central place. The main idea behind this feature is to re-use these codes to automatically generate the documentation for the API.
Note that this feature is optional and can simply be skipped. If you like to use
```php
public $code = 4711;
```
in your `Exceptions` this is completely fine.
However, if you like to use this feature, simply use
```php
public useErrorCode() {
return ApplicationErrorCodesTable::YOUR_ERROR_CODE_HERE;
}
```
in order to "link" the error code to this specific exception - and you're done..
=> Error codes

app/Containers/Authorization/Data/Migrations/2016_12_29_201047_create_permission_tables.php
Oracle database limit index name 30 characters. when eloquent create index the name is strip.
=> for oracle support - prevent duplicat index name in oracle

app/Containers/Authentication/Configs/authentication-container.php, app/Containers/Authentication/UI/API/Controllers/Controller.php, app/Containers/Authentication/UI/API/Tests/Functional/ProxyLoginTest.php, app/Containers/User/Mails/Templates/user-forgotPassword.blade.php
This PR removes some `env()` calls and replaces them with `Config::get()` calls..
See this issue here: https://github.com/apiato/apiato/issues/314
=> get rid of env() calls

app/Containers/User/UI/CLI/Commands/CreateAdminCommand.php
This PR fixes https://github.com/apiato/apiato/issues/284
It allows creating admins from the console with `php artisan apiato:create:admin`. It asks the user for basic information (name, email, password) and creates the user and assigns the admin role to it.
=> Create:Admin command

app/Ship/Criterias/Eloquent/ColumnBetweenDatesCriteria.php, app/Ship/Criterias/Eloquent/ThisBetweenDatesCriteria.php, app/Ship/Criterias/Eloquent/ThisLikeThatCriteria.php
Provided two new criteria that can be applied to several projects.
- _ThisBetweenDatesCriteria_: allows users to retrieve columns from a table whose `$field` is between `$start` and `$end` //name changed in second commit!
- _ThisLikeThatCriteria_: allows users to retrieve columns from a table where `$field` is like the given items in `$valueString`. Item separator and wildcard symbols can be changed by the user.
Both criteria are general purpose and can be re-used for other projects
Currently only manual testing has been done by creating a demoroute and testing both criteria with mock-data in a database. PHPUnit can be done if necessary.
- [] Breaking change (fix or feature that would cause existing functionality to not work as …
=> Added new Criteria - ThisLikeThat & ColumnBetweenDates

app/Containers/Localization/composer.json
- see http://php.net/manual/en/book.intl.php
- without this module, container throws Fatal: `Class 'Locale' not found`
=> Localization needs php intl module

app/Ship/Criterias/Eloquent/CountCriteria.php
Fix issues that can come up when using the default MySQL sql_mode=only_full_group_by, by removing the select * from the select clause.
Error example: Use criteria - ...new CountCriteria('unit')...
`SELECT *, count('unit') as 'total_count' FROM table GROUP BY 'unit'`
> SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db.table.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select *, count(unit) as total_count from table group by unit limit 15 offset 0)",
Removed the wildcard operator from the select to only output the counts.
The criteria should not require setting other modes per default. 
**Optionally** it …
=> Fix issues that can come up when using the default MySQL sql_mode

.github/README.md
Remove `codesponsor.io` link because it is shutting down
See this link for more information:
https://codesponsor.io/shutdown-notice/
See this other PR here
https://github.com/apiato/apiato/pull/360
that was closed because it would have actually deleted more details from the `README` file
=> remove codesponsor.io link

.env.example, app/Containers/Authentication/composer.json, app/Containers/Authorization/composer.json, app/Containers/Stripe/composer.json, app/Ship/Middlewares/Http/TrustProxies.php, composer.json, composer.lock, config/hashing.php, config/logging.php
This PR updates the framework to `Laravel 5.6`.
I will let this PR open for a few days in order to review it later.. Tests, however, pass.
Note to self - there are a few things to do if this PR is merged:
=> Laravel 5.6

config/app.php
this **PR** , removes  redundant **log configurations** from **app.php**
since **laravel 5.6** has [logging.php](https://github.com/laravel/laravel/blob/master/config/logging.php) file so there's no need to duplicate log configuration in **app.php**
=> [master] Remove redundant log configurations from app.php

app/Containers/Authentication/Actions/ProxyApiLoginAction.php, app/Containers/Authentication/Configs/authentication-container.php, app/Containers/Authentication/Data/Transporters/ProxyApiLoginTransporter.php, app/Containers/Authentication/Tasks/CheckIfUserIsConfirmedTask.php, app/Containers/Authentication/UI/API/Requests/LoginRequest.php, app/Containers/Authentication/UI/API/Tests/Functional/ProxyLoginTest.php, app/Ship/Parents/Models/UserModel.php
This PR allows users to log in with different attributes than `email`.
The feature is customizable and easy to extend.
http://docs.apiato.io/features/authentication/#login-with-custom-attributes
=> Login with Custom Fields

.gitattributes
Hi,
We can instruct Github not include these files when creating the release zip archive.
Since composer downloads the [zip](https://github.com/apiato/apiato/archive/v7.4.7.zip) from Github, it wont include these files when someone run `composer create-project` command.
You may also want to exclude `LICENSE` file, like laravel/laravel do
* You don't want your `.github` folder in our projects.
* We always delete these unwanted files and folders.
* Each project may have its own `CHANGELOG.md` , CI server configs and so on.
[Laravel/Laravel](https://github.com/laravel/laravel/blob/master/.gitattributes) and 
[Laravel/framework](https://github.com/laravel/framework/blob/5.6/.gitattributes) is already doing that and may be many others.
- [] New feature (non-breaking change which adds …
=> Don't publish these files and folders

app/Containers/Authorization/Traits/AuthenticationTrait.php
Builder instance in AuthenticationTrait now chains multiple attributes (if defined) correctly.
If multiple attributes were defined in authentication-container config, Passport authentication did not work correctly, since AuthenticationTrait checked only one attribute.
=> return builder with chained statements in AuthenticationTrait

app/Containers/Authentication/Providers/AuthProvider.php
Give api prefix to path of passport.
Url from laravel passport always /v1/oauth.
If someone use old code with prefix must call /v1/oauth. With this fix, must call /prefix/v1/oauth
=> Make passport respect api prefix

README.md, app/Containers/Documentation/Tasks/GenerateAPIDocsTask.php, app/Containers/Documentation/Traits/DocsGeneratorTrait.php
After changing php version from `7.4` to `7.2.5` some parts of the code started not working, for example we used to use `spread operator` in 7.4 but after the change of php version we had to remove this operation and write the code in another way.
An error was stopping us from generating apidoc
=> Avoid using spread operator for the sake of php version

app/Ship/Transporters/DataTransporter.php
As indicated in the DTO package documentation, additionalProperties key has to be defined in schema root array
https://github.com/fireproofsocks/dto/wiki/GettingStarted#refining-our-dto-schema
Related issue: #584
Fix default DataTransporter class additionalProperties.
=> Fix default transporter additional properties

app/Ship/core/Traits/HashIdTrait.php
Fixes the bug with the error:
`"array_key_exists() expects parameter 2 to be array, null given"`
I think, I've found a bug within the Request.
When you pass NULL value to a decodable field it gives an error like this:
`"array_key_exists() expects parameter 2 to be array, null given"`
It happened to me when I had a $decode property in my Request like this:
```
protected $decode = [
'data.id'
];
```
Then I've sent a query request to it with a `NULL` id value. The result was an error like I mentioned above:
```
"array_key_exists() expects parameter 2 to be array, null given"
```
I hope the pull request will be confirmed. If you have another solution. Please let us know 😊
=> HashId Issue

app/Ship/Configs/ide-helper.php
Fix "model_locations" for correct work "php artisan ide-helper:model" with Sections and Containers
Change field "model_locations" in config for ide-helper
In new version Apiato was added "Sections" for group Containers, and ide-helper can't generate because "model_locations" have wrong path to models
- Bug fix 
- My code follows the code style and structure of this project.
- I have updated the documentation accordingly.
=> model_locations in ide-helper.php

app/Containers/AppSection/Authorization/Data/Repositories/PermissionRepository.php, app/Containers/AppSection/Authorization/Data/Repositories/RoleRepository.php, app/Containers/AppSection/Authorization/Tasks/FindPermissionTask.php, app/Containers/AppSection/Authorization/Tasks/FindRoleTask.php, app/Containers/AppSection/User/Data/Repositories/UserRepository.php
There is an option in Laravel to replace the user model with your own model, but in the user container, the user repository automatically binds itself with the user model provided in the user container. Similarly, Spatie Laravel permission allows extending permission and role models, but these were bonded in a hardcoded way through the repository model function.
This pull request updates UserRepository, RoleRepository, PermissionRepository to fix the limitation explained above.
Another issue is in FindRoleTask and FindPermissionTask, it checks parameter type, to decide whether it is id or name. But this check fails when the id type is UUID. This pull request updates these tasks to check if param type is numeric or string of type UUID search in id column else in name column
I was trying to …
=> Update user, role and permission repository model bindings to allow custom model binding

app/Containers/AppSection/Authentication/Tasks/CallOAuthServerTask.php
Fix wrong api url
The old code did not take into account the API prefix, which led to a call to the wrong url.
=> fix wrong api url

app/Containers/AppSection/Authorization/UI/API/Requests/AssignUserToRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/AttachPermissionToRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/CreateRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/DeleteRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/DetachPermissionToRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/FindPermissionRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/FindRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/RevokeUserFromRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/SyncPermissionsOnRoleRequest.php, app/Containers/AppSection/Authorization/UI/API/Requests/SyncUserRolesRequest.php, app/Containers/AppSection/Authorization/UI/API/Tests/Functional/AttachPermissionsToRoleTest.php, app/Containers/AppSection/Authorization/UI/API/Tests/Functional/DetachPermissionsFromRoleTest.php, app/Containers/AppSection/Authorization/UI/API/Tests/Functional/RevokeUserFromRoleTest.php, app/Containers/AppSection/Authorization/UI/API/Tests/Functional/SyncPermissionsOnRoleTest.php
There is an option in Laravel spatie/laravel-permission package to define custom table names. But the default names are hardcoded in Requests and Tests of the Authorization container
I use custom table names for roles and permissions and associated API Requests and Tests fails with `table not found` error
=> Allow Role and Permission table bindings in Authorization Container (Requests, Tests)

.php-cs-fixer.dist.php
The ->notName() condition cannot be used 2 times.
More details: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/4716
=> Fix #775 Update .php-cs-fixer.dist.php
