php

I think this file was a result of some command log, may be remove ?

unecessary file

---

app/Containers/Application/Actions/CreateApplicationWithTokenAction.php
app/Containers/Application/Actions/ListAllAppsAction.php
app/Containers/Application/Tasks/FindApplicationByIdTask.php
app/Containers/Application/UI/API/Controllers/Controller.php
app/Containers/Authentication/Actions/WebAdminLoginAction.php
app/Containers/Authentication/Actions/WebLogoutAction.php
app/Containers/Authentication/Exceptions/LogoutFailedException.php
app/Containers/Authentication/Exceptions/MissingTokenException.php
app/Containers/Authentication/Exceptions/UpdateResourceFailedException.php
app/Containers/Authentication/Middlewares/VisitorsAuthentication.php
app/Containers/Authentication/Tasks/GenerateTokenFromClaimsTask.php
app/Containers/Authentication/Tasks/GetAuthenticatedUserTask.php
app/Containers/Authorization/UI/API/Transformers/RoleTransformer.php
app/Containers/Country/Actions/ListAllCountriesAction.php
app/Containers/Email/Actions/SetVisitorEmailAction.php
app/Containers/Email/Tasks/SendConfirmationEmailTask.php
app/Containers/Socialauth/Actions/SocialLoginAction.php
app/Containers/Socialauth/Tasks/UpdateUserSocialProfileTask.php
app/Port/Email/Abstracts/MailsAbstract.php
readme.md

There was a couple of missing variables inside some classes, I defined it as private but I am not sure about the scope.

Readme and DocBlock fixes

---

.env.travis
.gitignore
app/Containers/Authentication/UI/WEB/Controllers/Controller.php
app/Containers/Authentication/UI/WEB/Tests/Functional/UserLoginTest.php
app/Containers/Authentication/UI/WEB/Views/login.blade.php
app/Port/Tests/PHPUnit/Abstracts/WebTestCase.php
phpunit.xml

Add some fix errors to web login and abstract class for setup the web routes testing which only changes the `$baseUrl` property for the given one on the new `phpunit.xml` file.

Fix/login web update and add WebTestCase abstract

---

.gitignore

Other containers should have their own repository

only track Hello-API containers

---

app/Containers/Socialauth/UI/API/Controllers/Controller.php
app/Containers/Socialauth/UI/WEB/Controllers/Controller.php

Update imports to the new Ship structure

---

app/Containers/Authentication/UI/WEB/Controllers/Controller.php
app/Containers/Authentication/UI/WEB/Routes/main.php
app/Containers/Authentication/UI/WEB/Tests/Functional/UserLogoutTest.php

Hi @Mahmoudz,
This is a small fix for the logout WEB route. Based on [Laravel Docs](https://laravel.com/docs/5.3/upgrade) (search for POST To Logout) the logout should be a POST request and should give a redirect to login url, not a view.

Small Logout Fix

---

app/Containers/Authentication/Middlewares/WebAuthentication.php
app/Containers/Authentication/UI/WEB/Tests/Functional/ProtectedDashboardPage.php
app/Ship/Engine/Butlers/ContainersButler.php
app/Ship/Features/Configs/hello.php

Just that, the auth middleware should return a redirection to the login route, not a view... To make this to pass the tests, the PR #104 should be merged first...

Small fix for WebAuthentication middleware

---

app/Containers/Authentication/Middlewares/WebAuthentication.php
app/Containers/Authentication/UI/WEB/Tests/Functional/ProtectedDashboardPage.php
app/Ship/Engine/Butlers/ContainersButler.php
app/Ship/Engine/Loaders/MiddlewaresLoaderTrait.php
app/Ship/Features/Configs/hello.php
app/Ship/Parents/Providers/RoutesProvider.php

Hi @Mahmoudz , here are all the pull requests merged in one branch...

Hasher, load containers middlewares and WebAuthentication middleware fixes

---

app/Containers/Localization/Configs/localization.php
app/Containers/Localization/Resources/Languages/es/messages.php
resources/lang/es/auth.php
resources/lang/es/pagination.php
resources/lang/es/passwords.php
resources/lang/es/validation.php

Adding Spanish language support...

Add spanish language support

---

app/Containers/Authentication/Actions/WebAdminLoginAction.php
app/Containers/Authentication/Tasks/WebLoginTask.php
app/Containers/Authentication/UI/WEB/Views/login.blade.php

The WEB login is broken, this PR fix the issue...

Fix WEB login

---

app/Ship/Generator/Commands/ModelGenerator.php
app/Ship/Generator/GeneratorsServiceProvider.php
app/Ship/Generator/Stubs/model.stub

Creates a model in the Container of choice with correctly namespaced boilerplate model code ready to go.

New ModelGenerator

---

app/Ship/Generator/Commands/ActionGenerator.php
app/Ship/Generator/Commands/ControllerGenerator.php
app/Ship/Generator/Commands/EventGenerator.php
app/Ship/Generator/Commands/EventHandlerGenerator.php
app/Ship/Generator/Commands/ExceptionGenerator.php
app/Ship/Generator/Commands/ModelGenerator.php
app/Ship/Generator/Commands/RepositoryGenerator.php
app/Ship/Generator/Commands/RequestGenerator.php
app/Ship/Generator/Commands/RouteGenerator.php
app/Ship/Generator/Commands/TaskGenerator.php
app/Ship/Generator/Commands/TransformerGenerator.php
app/Ship/Generator/GeneratorCommand.php
app/Ship/Generator/GeneratorsServiceProvider.php
app/Ship/Generator/Interfaces/ComponentsGenerator.php
app/Ship/Generator/Stubs/controller.crud.api.stub
app/Ship/Generator/Stubs/controller.crud.web.stub
app/Ship/Generator/Stubs/controller.stub
app/Ship/Generator/Stubs/event.stub
app/Ship/Generator/Stubs/eventhandler.stub
app/Ship/Generator/Stubs/repository.stub
app/Ship/Generator/Stubs/request.stub
app/Ship/Generator/Stubs/route.stub
app/Ship/Generator/Stubs/task.stub
app/Ship/Generator/Stubs/transformer.stub
app/Ship/Generator/Traits/ParserTrait.php
docs/_docs/C.features/code-generator.md

- changed the generator command to a "wizard style" generator (e.g., propose command line prompts to the user to enter information)
- re-write the already existing generators
- add new generators
- update docs

Generator Feature

---

app/Ship/Engine/Traits/ResponseTrait.php
docs/_docs/B.general/contribution.md
docs/_docs/C.features/code-generator.md
docs/_docs/C.features/supported-parameters.md

This update updates the transformer when requesting an endpoint with `?filter=name;email;x` parameters.
Thereby, all "unwanted" fields are removed from the resultset.
Works with all currently provided Serializers (DataArraySerializer, JsonApiSerializer, ...)
This fixes issue #140 .

Filter Transformers

---

app/Containers/Socialauth/Tasks/CreateUserBySocialProfileTask.php
app/Containers/Socialauth/Tasks/FindSocialUserTask.php
app/Containers/Socialauth/Tasks/GetUserSocialProfileTask.php
app/Containers/Socialauth/Tasks/UpdateUserSocialProfileTask.php
app/Containers/Socialauth/UI/API/Requests/ApiAuthenticateRequest.php
composer.json
composer.lock
phpunit.xml

PHPUnit code coverage failed because of direct includes and use statement mismatches.

Fixed phpunit code coverage

---

app/Ship/Generator/Commands/RouteGenerator.php
app/Ship/Generator/Stubs/route.stub

fixing the route-http-method (was hard-coded to POST)

Small fix for RouteGenerator

---

app/Containers/Bootstrap/composer.json
app/Ship/composer.json
composer.json
docs/_docs/C.features/authentication.md
docs/_docs/C.features/authorization.md
docs/_docs/C.features/container-installer.md
docs/_docs/C.features/pagination.md
docs/_docs/C.features/payments.md
docs/_docs/C.features/query-parameters.md
docs/_docs/C.features/queues.md
docs/_docs/C.features/tests-helpers.md
docs/_docs/C.features/user-registration.md
docs/_docs/C.features/validation.md
docs/_docs/D.components/repositories.md
docs/_docs/D.components/requests.md
docs/_docs/D.components/transformers.md

This PR adds some kind of `container installer`. This installer, in turn, allows application developer to include and automatically install and update containers from 3rd party developers using composer.

Container Installer

---

app/Containers/Bootstrap/composer.json
app/Containers/composer.json
composer.json
docs/_docs/C.features/container-installer.md

Remove `Bootstrap` container as discussed

Remove Bootstrap Container

---

app/Ship/Generator/Stubs/repository.stub

as discussed in the slack channel.. my own fault :(

fix in repository stub

---

app/Ship/Parents/Requests/Request.php
docs/_docs/D.components/requests.md

As discussed in #186 : 
I have added a `sanitizeInput()` method to the `Request` class. This method allows to specify a list of fields (in the dot notation). These fields are extracted and returned.
I have updated the docs as well (with an example)!

SanitizeInput method for the Request class

---

app/Containers/Authentication/Actions/ProxyApiLoginAction.php
app/Containers/Authentication/Actions/WebAdminLoginAction.php
app/Containers/Authentication/Actions/WebLoginAction.php
app/Containers/Authentication/Configs/authentication.php
app/Containers/Authentication/Exceptions/UserNotConfirmedException.php
app/Containers/Authentication/Tasks/CheckIfUserIsConfirmedTask.php
app/Ship/Exceptions/DeleteResourceFailedException.php
docs/_docs/C.features/authentication.md

Allow only "confirmed" users to login to your application.
Application throws an additional exception, if the user is not confirmed yet...

Allow only "confirmed" Users to login

---

app/Containers/Authentication/Actions/ProxyApiLoginAction.php
app/Containers/Authentication/Actions/WebAdminLoginAction.php
app/Containers/Authentication/Actions/WebLoginAction.php
app/Containers/Authentication/Configs/authentication.php
app/Containers/Authentication/Exceptions/UserNotConfirmedException.php
app/Containers/Authentication/Tasks/CheckIfUserIsConfirmedTask.php
app/Containers/Authentication/UI/API/Tests/Functional/ProxyLoginTest.php
app/Ship/Exceptions/DeleteResourceFailedException.php
app/Ship/Tests/PhpUnit/TestsAuthHelperTrait.php
docs/_docs/C.features/authentication.md

Allow only "confirmed" users to login to your application.
Application throws an additional exception, if the user is not confirmed yet...

Allow only confirmed users to login

---

app/Ship/Parents/Repositories/Repository.php

Revert "Disable Pagination on Requests"

---

app/Ship/Seeders/SeedDeploymentData.php

Adds a new seeder to automatically generate data needed for a deployment of the application (e.g., create an `admin` user, create some `Settings`, whatever...)
Please see other PR here as well https://github.com/apiato/core/pull/4

new seeder

---

docs/_docs/components/models.md

Hi, as I've stumbled about the naming issues on my first day with apiato i thought i'd add a small paragraph to your doc explaining the issue and linking to the repository page.
Additionally I've added a small section about casting inside of the model.
- Naming: Ran straight into the issue of naming because did not realise that there is a specific convention underneath the model naming. Thus I've added a small reminder under the rules section to help fellow new users of apiato. Issue: [here](https://github.com/apiato/apiato/issues/216)
- Casting: The documentation of the model was pretty thin and as a new user without experience in Laravel i'd have found the information about casting with a link useful.
- [] New feature (non-breaking …

Updated the model docs - cast section added and naming of models mentioned

---

docs/_docs/getting-started/overview.md
docs/_docs/getting-started/porto-sap.md
docs/_docs/getting-started/requests.md
docs/_docs/getting-started/responses.md

getting-started-Tables

---

docs/_docs/getting-started/overview.md
docs/_docs/getting-started/porto-sap.md
docs/_docs/getting-started/requests.md
docs/_docs/getting-started/responses.md

Revert "getting-started-Tables"

---

docs/_docs/getting-started/porto-sap.md
docs/_docs/getting-started/responses.md

fix-portSap&responseFILES-contentTables

---

app/Containers/Authorization/UI/API/Tests/Functional/AssignUserToRoleTest.php
app/Containers/Authorization/UI/API/Tests/Functional/RevokeUserFromRoleTest.php
app/Containers/Authorization/UI/API/Tests/Functional/SyncUserRolesTest.php

- `model_has_roles` table does not have `user_id` field
- Different kind of test database may return roles of user in different order.

Fix bugs in some test file

---

docs/_docs/getting-started/overview.md
docs/_docs/getting-started/porto-sap.md
docs/_docs/getting-started/requests.md
docs/_docs/getting-started/responses.md

Add and Fix Table Content of Getting started Folder Files

---

app/Containers/Wepay/Actions/CreateWepayAccountAction.php
app/Containers/Wepay/Data/Migrations/2016_07_08_110947_create_wepay_accounts_table.php
app/Containers/Wepay/Data/Repositories/wepayAccountRepository.php
app/Containers/Wepay/Exceptions/ObjectNonChargeableException.php
app/Containers/Wepay/Exceptions/PaymentFailedException.php
app/Containers/Wepay/Exceptions/PaymentMethodNotFoundException.php
app/Containers/Wepay/Exceptions/WepayAccountNotFoundException.php
app/Containers/Wepay/Exceptions/WepayApiErrorException.php
app/Containers/Wepay/Models/WepayAccount.php
app/Containers/Wepay/Providers/MainServiceProvider.php
app/Containers/Wepay/Tasks/ChargeWithWepayTask.php
app/Containers/Wepay/Tasks/CreateWepayCustomerTask.php
app/Containers/Wepay/Tests/TestCase.php
app/Containers/Wepay/UI/API/Controllers/Controller.php
app/Containers/Wepay/UI/API/Requests/CreateWepayAccountRequest.php
app/Containers/Wepay/UI/API/Routes/CreateWepayAccount.v1.private.php
app/Containers/Wepay/UI/API/Tests/Functional/CreateWepayAccountTest.php
app/Containers/Wepay/composer.json

We have added new Wepay container, please check below details.
Wepay container look like same as your default containers stripe. In this container required this "kevinem/wepay-laravel": "^0.1.0". they installation with this cmd : composer update.
This container already with PHPUNIT Testing 
In this container changes in .env file, define your configuration in .env file.
Please check: App/containers/wepay

Wepay payment gateway container.

---

docs/_docs/components/controllers.md

Minor Typo (accespts -> accepts)

---

docs/_docs/miscellaneous/contribution.md

update contribution guide

---

docs/_docs/miscellaneous/contribution.md

add more details to contribution guide

---

.github/CONTRIBUTING.md
.github/README.md
docs/_docs/features/admin-dashboard.md
docs/_docs/getting-started/installation.md

Docs and some typo fixes

---

CHANGELOG.md

Update Changelog file

---

app/Containers/Payment/UI/API/Controllers/Controller.php
app/Containers/Payment/UI/API/Requests/GetPaymentAccountDetailsRequest.php

corrected a classname for the request

correct classname

---

CHANGELOG.md
docs/_docs/features/code-generator.md

Docs for the `Custom Stub` feature [here](https://github.com/apiato/core/pull/15)
Cheers

[Docs] Custom Stubs

---

docs/_docs/components/actions.md
docs/_docs/components/events.md
docs/_docs/components/exceptions.md
docs/_docs/components/jobs.md
docs/_docs/components/languages.md
docs/_docs/components/middlewares.md
docs/_docs/components/models.md
docs/_docs/components/repositories.md
docs/_docs/miscellaneous/faq.md

Rewrote smaller sections in the docs, updated some of the links to the old laravel docs to 5.5 (will continue to do this later on) and rewrote parts of sentences that did not feel quite right. Added a link to the magical calls pages.

Fixed a few minor typos, added & updated links

---

bootstrap/app.php

Added the proposed change to use the newer serialization precision mode if the php version supports it.
See issue #257 

Added the serialization precision to bootstrap/app.php

---

app/Containers/Authorization/Data/Seeders/AuthorizationDefaultUsersSeeder_3.php

fix double encrypted the password     
App\Containers\User\Tasks\CreateUserByCredentialsTask

fix double encrypted the password

---

app/Containers/Authentication/Exceptions/OAuthException.php

Correct php doc

---

app/Containers/User/UI/API/Routes/ForgotPassword.v1.public.php
app/Containers/User/UI/API/Routes/ResetPassword.v1.public.php

Moves the routes `password-xyz` to `password/xyz` for better accessibility

Move Routes

---

app/Containers/Authorization/Traits/AuthorizationTrait.php
docs/_docs/features/authorization.md

This adds a `getRoleLevel()` method to the `User` (or rather one `Trait` the `User` model implements).

GetRoleLevel for User

---

app/Containers/User/Actions/ForgotPasswordAction.php
app/Containers/User/Actions/ResetPasswordAction.php
app/Containers/User/Tasks/CreatePasswordResetTask.php
app/Containers/User/Tasks/FindUserByEmailTask.php

Minor fixes

---

.github/CONTRIBUTING.md

Updated the url to from `apiato.io` -> `docs.apiato.io`

Fixed Site URL in the contributing file

---

app/Containers/Authentication/Actions/ProxyApiLoginAction.php
app/Containers/Authentication/Actions/ProxyApiRefreshAction.php
app/Containers/Authentication/Data/Transporters/ProxyApiLoginTransporter.php
app/Containers/Authentication/Data/Transporters/ProxyRefreshTransporter.php
app/Containers/Authentication/UI/API/Controllers/Controller.php
composer.lock

This PR moves the `Authentication/Transporters` folder to `Authentication/Data/Transporters` as described in the docs here: http://docs.apiato.io/components/transporters/

Move Transporter folder to Data/Transporter

---

app/Containers/Authentication/Data/Transporters/ProxyApiLoginTransporter.php
app/Containers/Authentication/Data/Transporters/ProxyRefreshTransporter.php

This PR adds the `type = object` to the already defined `Transporter`s

Add TYPE to Transporter

---

app/Containers/Debugger/Tasks/QueryDebuggerTask.php

The QueryDebugger object was throwing an error "Object of class DateTime could not be converted to string" when a DateTime object was been set as binding of a Query.
With this Pull Request, the QueryDebugger is handling the bindings the same way as the Connection::prepareBindings(array $bindings) does.
With phpunit and the QUERIES_DEBUG environment variable set to true.

Fixed error in QueryDebugger when bindings were DateTime objects or boolean values

---

app/Containers/Authentication/composer.json

Update laravel/passport to latest version

---

CHANGELOG.md
app/Containers/Payment/Contracts/ChargeableInterface.php
app/Containers/Payment/Contracts/PaymentChargerInterface.php
app/Containers/Payment/Data/Migrations/2018_01_01_000001_create_payment_transactions_table.php
app/Containers/Payment/Data/Repositories/PaymentTransactionRepository.php
app/Containers/Payment/Gateway/PaymentsGateway.php
app/Containers/Payment/Models/PaymentTransaction.php
app/Containers/Payment/Traits/ChargeableTrait.php
app/Containers/Payment/Traits/MockablePaymentsTrait.php
app/Containers/Stripe/Tasks/ChargeWithStripeTask.php
app/Containers/Stripe/Tests/Unit/ChargeUserWithStripeTest.php
app/Containers/Wepay/Tasks/ChargeWithWepayTask.php
composer.lock

This PR adds `PaymentTransactions` for the `Payment` container.
1) It adds a new `Model` (with migration file) that stores transactions.
2) It changes the `Contracts` of the `charge()` methods to return a `PaymentTransaction`. This means, that the `ChargeWithXTask` classes (e.g., `ChargeWithStripeTask`) **must** return a `PaymentTransaction` class, instead of an array (as currently).
3) The `PaymentTransaction` is automatically stored to the database in order to keep track of all transactions, one user made. Note that you (as a developer of a Payment Gateway like Stripe, PayPal, ...) only need to fill in some basic information (like the status of the transaction or the transaction id). Most of the other details (e.g., the name of the gatway that handled this transaction or the amount the …

Payment Transactions

---

app/Ship/Configs/apiato.php

to disable "apiato wrong caller style" notification

add config flag

---

app/Ship/Kernels/HttpKernel.php

this **PR** ,adds **signed** middleware to **Http Kernel**
cause the **signed route** feature is added in [laravel 5.6.12](https://github.com/laravel/framework/pull/23519)

[master] Add signed middleware to kernel.php

---

.github/README.md

Changed readme from `Laravel 5.5` to `Laravel 5.6` 
- [] Documentation

update readme to laravel 5.6

---

app/Containers/Authentication/Actions/ProxyApiLoginAction.php
app/Containers/Authentication/Configs/authentication-container.php
app/Containers/Authentication/Data/Transporters/ProxyApiLoginTransporter.php
app/Containers/Authentication/Tasks/CheckIfUserIsConfirmedTask.php
app/Containers/Authentication/UI/API/Requests/LoginRequest.php
app/Containers/Authentication/UI/API/Tests/Functional/ProxyLoginTest.php
app/Ship/Parents/Models/UserModel.php

This PR allows users to log in with different attributes than email.
The feature is customizable and easy to extend.
http://docs.apiato.io/features/authentication/#login-with-custom-attributes

Login with Custom Fields

---

app/Containers/Authentication/Exceptions/AuthenticationException.php
app/Containers/Authentication/Exceptions/LoginFailedException.php
app/Containers/Authentication/Exceptions/OAuthException.php
app/Containers/Authentication/Exceptions/RefreshTokenMissedException.php
app/Containers/Authentication/Exceptions/UserNotConfirmedException.php
app/Containers/Authentication/UI/API/Tests/Functional/ProxyRefreshTest.php
app/Containers/Authorization/Exceptions/PermissionNotFoundException.php
app/Containers/Authorization/Exceptions/RoleNotFoundException.php
app/Containers/Documentation/Exceptions/NoDocTypesFoundException.php
app/Containers/Localization/Exceptions/UnsupportedLanguageException.php
app/Containers/Payment/Exceptions/ChargerTaskDoesNotImplementInterfaceException.php
app/Containers/SocialAuth/Exceptions/AccountFailedException.php
app/Containers/Stripe/Exceptions/ObjectNonChargeableException.php
app/Containers/Wepay/Exceptions/WepayApiErrorException.php

Slightly adapt Exception Messages to be more meaningful

Better Exception Messages

---

app/Containers/Localization/Tests/ApiTestCase.php
app/Containers/Localization/Tests/TestCase.php
app/Containers/Localization/Tests/Unit/GetLocalizationsTest.php
app/Containers/Localization/UI/API/Tests/Functional/CheckLocalizationMiddlewareTest.php

Added a few tests in order to test the `Localization` Container

add tests to Localization Container

---

app/Containers/Authentication/UI/API/Routes/Logout.v1.public.php
app/Containers/Settings/UI/API/Routes/GetAllSettings.v1.private.php
app/Containers/User/UI/API/Routes/CreateAdmin.v1.private.php
app/Containers/User/UI/API/Routes/DeleteUser.v1.private.php

Updated documentation and fixed some typos.
I've added the tittle that is required in the @api tag so that the logout documentation is rendered.
I tested recreating the docs and checking changes.

Fix logout docs not rendered and some typos (#444).

---

app/Containers/Debugger/composer.json
app/Ship/Providers/ShipProvider.php
app/Ship/composer.json

Allow exclude barryvdh/laravel-debugbar on composer install --no-dev

allow exclude barryvdh/laravel-debugbar on composer install --no-dev

---

app/Containers/Debugger/Configs/debugger.php

if set to ` 'console' => 'false',  `
```
if ($consoleOutputEnabled) {
dump($result);
}
```
`if('false')` //this results in true
So the settings must be set to boolean

config in boolean format

---

config/auth.php

changed token driver in /config/Auth.php from "token" to "passport"
this is a breaking issue (auth not working for API)

Fix auth. issue - change token driver to passport

---

app/Ship/core/Loaders/FactoriesLoaderTrait.php

This PR fixes the issue with FactoryMixer path on unit testing execution.
I used the fixes that proposed in [this](https://github.com/apiato/core/pull/129#issue-293068376) unmerged pull request on now deprecated [apiato/core](https://github.com/apiato/core).
It fixes [this](https://github.com/apiato/apiato/issues/507#issue-476714365) open issue.
All credits goes to:
[vunnu](https://github.com/vunnu) for [this](https://github.com/apiato/core/pull/129#issue-293068376) pull request and [JulianBustamante](https://github.com/JulianBustamante) for [this](https://github.com/apiato/core/pull/124#issue-232691311) one.
- [] I have …

Fix FactoryMixer path on unit testing execution

---

app/Ship/Kernels/HttpKernel.php

Maybe should use \App\Ship\Middlewares\Http\Authenticate::class class name
Fix priority Authenticate

fix: fix priority authenticate middleware name

---

app/Containers/Authentication/UI/API/Tests/Functional/ApiLogoutTest.php
app/Containers/Authentication/UI/API/Tests/Functional/ProxyLoginTest.php
app/Containers/Authentication/UI/API/Tests/Functional/ProxyRefreshTest.php
app/Containers/SocialAuth/Exceptions/AccountFailedException.php
app/Containers/SocialAuth/Exceptions/UnsupportedSocialAuthProviderException.php
app/Containers/SocialAuth/Tasks/CreateUserBySocialProfileTask.php
app/Containers/SocialAuth/Tasks/FindUserSocialProfileTask.php

fixed Composer v2.0 autoload compatibility issue in some files

---

app/Containers/Debugger/Configs/debugger.php

Correct logs path

---

app/Containers/Authentication/Actions/ProxyApiLoginAction.php
app/Containers/Authentication/Configs/authentication-container.php
app/Containers/Authentication/Data/Transporters/ProxyApiLoginTransporter.php
app/Containers/Authentication/Tasks/CheckIfUserIsConfirmedTask.php
app/Containers/Authentication/Tasks/ExtractLoginCustomAttributeTask.php
app/Containers/Authentication/UI/API/Tests/Functional/ProxyLoginTest.php
app/Containers/User/Models/User.php

Reimplement "login with custom attribute" feature that was in the previous versions of Apiato and was removed due to bugs.
- [*] New feature (non-breaking change which adds functionality).
- [*] My code follows the code style and structure of this project.
- [*] I have updated the tests accordingly.

Reintroduce login with multiple fields

---

app/Containers/Authorization/Traits/AuthenticationTrait.php
app/Containers/Authorization/Traits/AuthorizationTrait.php

https://github.com/apiato/apiato/issues/551

Fix authentication and authorization traits.

---

app/Containers/Authentication/Actions/ApiLogoutAction.php

Changing getHeader() to getClaim() retrieves the token to be revoked.
After updating to v 9, logout failed with OutOfBoundsException and message "Requested header is not configured". Seems to be an issue with Lcobucci\JWT\Token, but I didn't find any changes in that package. Changing the method fixed it for me.

Fix Logout

---

app/Ship/core/composer.json

Warning: Ambiguous class resolution, "Fruitcake\Cors\CorsServiceProvider" was found 2x: in "/vendor/barryvdh/laravel-cors/src/CorsServiceProvider.php" and "/vendor/fruitcake/laravel-cors/src/CorsServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "Fruitcake\Cors\HandleCors" was found 2x: in "/vendor/barryvdh/laravel-cors/src/HandleCors.php" and "/vendor/fruitcake/laravel-cors/src/HandleCors.php", the first will be used.

Prevent composer warning message

---

app/Containers/Authorization/Traits/AuthenticationTrait.php
app/Containers/Authorization/Traits/AuthorizationTrait.php

Revert "Fix authentication and authorization traits."

---

app/Containers/Documentation/Tasks/GenerateAPIDocsTask.php
app/Containers/Documentation/Traits/DocsGeneratorTrait.php
composer.json

Fixes some code which were using "Process" component of Symphony.
The bug appeared after Apiato upgraded to newer versions of Laravel thus upgrading to a newer version of Symphony.
This fixes a problem with docs which would be generated without header.

Fix: apidoc now correctly generate docs with header included

---

app/Containers/Documentation/ApiDocJs/shared/header.template.md

Fix invalid json formatting in document header template

---

app/Containers/Authentication/Tests/WebTestCase.php

Fix declaration inconsistency in overriding method.
This inconsistency was preventing the use of
`php artisan ide-helper:models`
command and would throw
`  Declaration of App\Containers\Authentication\Tests\WebTestCase::setUp() must be compatible with App\Ship\Parents\Tests\PhpUnit\TestCase::setUp(): void  `
Fix ide helper error

Fix declaration inconsistency

---

app/Containers/Authentication/Providers/AuthProvider.php

Fixed registration password authorize routes.
`Passport` authorize pages display as json because of `api` middleware and `ValidateJsonContent`

Fix passport authorize routes

---

app/Ship/core/Traits/CallableTrait.php

As indicated in the DTO package documentation, required properties must be passed to the object constructor
https://github.com/fireproofsocks/dto/wiki/GettingStarted#refining-our-dto-schema
https://github.com/fireproofsocks/dto/wiki/Object#required
Related issue: https://github.com/apiato/apiato/issues/585
This fix the request to transporter conversion when using custom transporter with required properties

Fix request to transporter conversion

---

app/Ship/core/Abstracts/Transporters/Transporter.php
app/Ship/core/Generator/Stubs/transporter.stub

As indicated in the DTO package documentation, additionalProperties key has to be defined in schema root array
https://github.com/fireproofsocks/dto/wiki/GettingStarted#refining-our-dto-schema
Related issue: #584
Fix Transporter abstract class to allow use additionalProperties set to false.
Transporter stub has also been fixed.

Fix transporter additional properties

---

app/Containers/Localization/Providers/MainServiceProvider.php

Since Laravel autodiscover feature is disabled on Apiato, Carbon ServiceProvider is not loaded and app language is not applied on Carbon instances
Fix Carbon language.
Laravel autodiscover feature should be enabled again in the future to avoid these issues.

Fix Carbon language

---

app/Ship/core/Abstracts/Transporters/Transporter.php
app/Ship/core/Generator/Stubs/transporter.stub

Reverts apiato/apiato#600
Additional R&D is required.

Revert "Fix transporter additional properties"

---

app/Ship/Transporters/DataTransporter.php

Reverts apiato/apiato#601
Additional R&D is required.

Revert "Fix default transporter additional properties"

---

app/Containers/Authentication/Tasks/CallOAuthServerTask.php

Add language header to oauth request
In order to get auth exceptions in correct app.locale language, oauth request has to have HTTP_ACCEPT_LANGUAGE header defined.

add language header to oauth task

---

resources/lang/fa/auth.php
resources/lang/fa/pagination.php
resources/lang/fa/passwords.php
resources/lang/fa/validation.php

about issue :  #595 
I just translated locale files for the Persian language
special thanks to all members for building this great project <3

persian translation files 

---

app/Containers/AppSection/Authorization/Data/Seeders/AuthorizationGivePermissionsToRolesSeeder_3.php

- Role model was hard coded and that was ignoring, customized  role model which spetie package allows
- Simple update to use role model as specified in configuration file, instead using directly
It allows use of custom role model, instead of using role model that is provided by default

Use role model from configuration

---

app/Containers/AppSection/Authentication/UI/API/Requests/RegisterUserRequest.php
app/Containers/AppSection/User/Models/User.php
app/Containers/AppSection/User/Providers/MainServiceProvider.php
app/Containers/AppSection/User/UI/API/Requests/UpdateUserPasswordRequest.php

[//]: # (Please include a summary of the change and which issue is fixed.  )
[//]: # (Please also include relevant motivation and context.  )
[//]: # (List any dependencies that are required for this change.)

API-761-move-password-rules-to-service-provider

---

phpunit.xml

[//]: # (Please include a summary of the change and which issue is fixed.  )
[//]: # (Please also include relevant motivation and context.  )
[//]: # (List any dependencies that are required for this change.)

API-1086-update-php-unit-configs

---

app/Containers/AppSection/Authentication/UI/API/Controllers/LoginProxyForWebClientController.php
app/Containers/AppSection/Authentication/UI/API/Controllers/RefreshProxyForWebClientController.php
app/Containers/AppSection/Authentication/UI/API/Controllers/RegisterUserController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/AssignRolesToUserController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/CreateRoleController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/FindPermissionByIdController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/FindRoleByIdController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/GivePermissionsToRoleController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/GivePermissionsToUserController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/ListPermissionsController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/ListRolePermissionsController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/ListRolesController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/ListUserPermissionsController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/ListUserRolesController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/RemoveUserRolesController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/RevokeRolePermissionsController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/RevokeUserPermissionsController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/SyncRolePermissionsController.php
app/Containers/AppSection/Authorization/UI/API/Controllers/SyncUserRolesController.php
app/Containers/AppSection/User/UI/API/Controllers/FindUserByIdController.php
app/Containers/AppSection/User/UI/API/Controllers/GetUserProfileController.php
app/Containers/AppSection/User/UI/API/Controllers/ListUsersController.php
app/Containers/AppSection/User/UI/API/Controllers/UpdatePasswordController.php
app/Containers/AppSection/User/UI/API/Controllers/UpdateUserController.php
app/Ship/Configs/apiato.php
app/Ship/Tests/Unit/Configs/ApiatoConfigTest.php
composer.lock

[//]: # (Please include a summary of the change and which issue is fixed.  )
[//]: # (Please also include relevant motivation and context.  )
[//]: # (List any dependencies that are required for this change.)

Api 1150 improve tansformers

---

app/Containers/AppSection/Authentication/Tests/Functional/API/LoginProxyForWebClientTest.php
app/Containers/AppSection/Authentication/Tests/Unit/Classes/LoginFieldParserTest.php
app/Containers/AppSection/Authentication/Tests/Unit/Values/LoginFieldTest.php
app/Containers/AppSection/Authorization/Data/Collections/PermissionCollection.php
app/Containers/AppSection/Authorization/Data/Collections/RoleCollection.php
app/Containers/AppSection/Authorization/Models/Permission.php
app/Containers/AppSection/Authorization/Models/Role.php
app/Containers/AppSection/User/Data/Collections/UserCollection.php
app/Containers/AppSection/User/Models/User.php
app/Containers/AppSection/User/UI/API/Transformers/UserAdminTransformer.php
app/Ship/Configs/fractal.php
app/Ship/Configs/notification.php
app/Ship/Helpers/readme.md
app/Ship/Parents/Collections/EloquentCollection.php
composer.lock

[//]: # (Please include a summary of the change and which issue is fixed.  )
[//]: # (Please also include relevant motivation and context.  )
[//]: # (List any dependencies that are required for this change.)

API-1125-Add-custom-eloquent-collections
